/* Generated By:JavaCC: Do not edit this line. ProjLangParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ProjLangParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ASS = 5;
  /** RegularExpression Id. */
  int EQU = 6;
  /** RegularExpression Id. */
  int ADD = 7;
  /** RegularExpression Id. */
  int SUB = 8;
  /** RegularExpression Id. */
  int MUL = 9;
  /** RegularExpression Id. */
  int DIV = 10;
  /** RegularExpression Id. */
  int APHO = 11;
  /** RegularExpression Id. */
  int LPAR = 12;
  /** RegularExpression Id. */
  int RPAR = 13;
  /** RegularExpression Id. */
  int LFLBR = 14;
  /** RegularExpression Id. */
  int RFLBR = 15;
  /** RegularExpression Id. */
  int SEMCOL = 16;
  /** RegularExpression Id. */
  int NOT = 17;
  /** RegularExpression Id. */
  int LT = 18;
  /** RegularExpression Id. */
  int LOR = 19;
  /** RegularExpression Id. */
  int LAND = 20;
  /** RegularExpression Id. */
  int IF = 21;
  /** RegularExpression Id. */
  int THEN = 22;
  /** RegularExpression Id. */
  int ELSE = 23;
  /** RegularExpression Id. */
  int LET = 24;
  /** RegularExpression Id. */
  int VAL = 25;
  /** RegularExpression Id. */
  int IN = 26;
  /** RegularExpression Id. */
  int END = 27;
  /** RegularExpression Id. */
  int FUN = 28;
  /** RegularExpression Id. */
  int WHILE = 29;
  /** RegularExpression Id. */
  int DO = 30;
  /** RegularExpression Id. */
  int TRUE = 31;
  /** RegularExpression Id. */
  int FALSE = 32;
  /** RegularExpression Id. */
  int ID = 33;
  /** RegularExpression Id. */
  int NUM = 34;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\":=\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"`\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"!\"",
    "\"<\"",
    "\"|\"",
    "\"&\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"let\"",
    "\"val\"",
    "\"in\"",
    "\"end\"",
    "\"fun\"",
    "\"while\"",
    "\"do\"",
    "\"true\"",
    "\"false\"",
    "<ID>",
    "<NUM>",
  };

}
